name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main  # or 'master' or any branch you want to trigger deployment from
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3

      - name: Build and Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for GitHub integrations (commenting on PRs, etc.)
          action: "upload"
          app_location: "."                     # Location of your static app source files (index.html, etc.)
          api_location: ""                      # Leave empty if no backend API
          output_location: ""                   # Leave empty unless using a build tool (e.g. dist, build)
          skip_deploy_on_missing_secrets: true
