name: Azure Deployment

# Trigger the workflow on push to the main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v2

      # Step 2: Setup Azure CLI (if needed for deployment)
      - name: Set up Azure CLI
        uses: azure/setup-azure-cli@v1
        with:
          azure-cli-version: '2.29.0'

      # Step 3: Log in to Azure using the deployment token
      - name: Azure Login
        run: |
          echo "${{ secrets.AZURE_DEPLOYMENT_TOKEN }}" | az login --service-principal --username ${{ secrets.AZURE_CLIENT_ID }} --password-stdin --tenant ${{ secrets.AZURE_TENANT_ID }}
        env:
          AZURE_DEPLOYMENT_TOKEN: "9a089a9685e277866c3f63aa9da530e5e0d2e644ee94638069d65e811568e39906-d8d7bcac-2f06-4eb8-9ad9-cb8279c43e9701e191804fc81d1e"  # Replace with your Azure token directly

      # Step 4: Deploy content to Azure (replace with your actual deployment commands)
      - name: Deploy to Azure
        run: |
          echo "Deploying content to Azure..."
          # Replace this with your Azure deployment command, for example using az CLI or any other method
          az webapp deployment source config-zip --resource-group your-resource-group --name your-app-name --src your-package.zip
        env:
          AZURE_DEPLOYMENT_TOKEN: "9a089a9685e277866c3f63aa9da530e5e0d2e644ee94638069d65e811568e39906-d8d7bcac-2f06-4eb8-9ad9-cb8279c43e9701e191804fc81d1e"  # Again, directly embed the token here

      # Optional: Step to log completion
      - name: Deployment Complete
        run: |
          echo "Deployment completed successfully."
